public class Carro {

    Modelo modelo = new modelo();

	Placa placa = new placa();

	Cor cor = new cor();

	Marca marca = new marca();

	public placa get=() {
		return this.=;
	}

	public void set=(placa =) {
		this.= = =;
	}

	public cor get=() {
		return this.=;
	}

	public void set=(cor =) {
		this.= = =;
	}

	public marca get=() {
		return this.=;
	}

	public void set=(marca =) {
		this.= = =;
	}


	public modelo get=() {
		return this.=;
	}

	public void set=(modelo =) {
		this.= = =;
	}
	

}